# Generated by Django 2.2 on 2019-04-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=10, unique=True)),
                ('category_title', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_code_type', models.CharField(choices=[('ICD_10', 'icd-10'), ('ICD_9', 'icd-9')], default='ICD_10', max_length=10)),
                ('diagnosis_code', models.CharField(max_length=15, unique=True)),
                ('abbreviated_description', models.CharField(max_length=400)),
                ('full_description', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_category', to='diagnosis_api.DiagnosisCategory')),
            ],
            options={
                'ordering': ('diagnosis_code_type', 'diagnosis_code'),
            },
        ),
    ]
