# Generated by Django 2.2 on 2019-04-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis_api', '0002_auto_20190404_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosiscategory',
            name='category_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
